### ISSUE TITLE
Error installing elastic agent on new Azure VM

### ISSUE THREAD

**Issue by aliensojurner** [gocd/azure-elastic-agent-plugin#6]
##### Issue Type

- Bug Report

##### Summary

I'm getting this error with the Go Azure Elastic Agent not installing the agent on the VM that it spins up? I'm not even sure where to look to find this information for it to be edited. 

Failed to install go agent on gocd-azure-c413d70b-f776-4d01-8435-5b77799a3ddf for job settingsrouter_experiment/2/build/1/windows due to error: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> plugin_id  [in template "windows_install_go_agent.template.flth" at line 20, column 17]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${plugin_id}  [in template "windows_install_go_agent.template.flth" at line 20, column 15]

###### Basic environment details

* Go Version: `20.1`
* JAVA Version: `13`
* OS: Windows server 2012R2

##### Steps to Reproduce

1. Set up elastic agent profile correctly
2. Run a build to have it spin up a VM in Azure based on a correct image
3. View the VM in Azure stuck in Creating state
4. Error in GO stating that it could not install the elastic agent on the newly created VM

##### Expected Results
It should install the agent based on the elastic agent plugin
##### Actual Results

I get the error posted above where it failed due to not being able to install the agent on the new vm.

**Comment by arvindsv** [comment]
@aliensojurner Can you see if this release helps? https://github.com/gocd/azure-elastic-agent-plugin/releases/tag/v1.0.0-8-exp

**Comment by aliensojurner** [comment]
Thank you so much for the quick turn around. The error no longer seems to pop up. The VM now gets to a state of "Running" like it should, but it never appears in the Elastic Agent page. It does appear in the static agents page though and requires me to set resources like a regular static agent. I will open a new issue for the problems I'm now seeing since the specific issue here is resolved.
