### ISSUE TITLE
Issues after plugin installs elastic agent into new Azure VM

### ISSUE THREAD

**Issue by aliensojurner** [gocd/azure-elastic-agent-plugin#7]
When the elastic agent plugin creates a virtual machine and installs the agent into the VM, it appears under the static agent list and not the elastic agent list. This requires me to add resources for the agent for it to build, and doesn't get removed when the build is done. The VM is correctly removed, but since it's a static agent it would just show as lost contact in the GO portal. 

To add to the complication, is there any possible way to have it create the agent so that it runs under a specific user account and not Local System? Would there be some way to implement a way for me to edit a file to provide the user account and password that the agent service should run under?

If there is any specific information you require about our setup just let me know.

**Comment by arvindsv** [comment]
@aliensojurner I'll take a look tomorrow. Meanwhile, can you take a look at this file:

https://github.com/gocd/azure-elastic-agent-plugin/blob/1cf583d85809f86e0da502d95478affe17e88794/src/main/resources/windows_install_go_agent.template.flth

That's the template used to create an agent. I'm surprised it is not showing up as an elastic agent. There is an agent autoregister properties file whose contents are supposed to get it to register as an elastic agent. If possible, please check to see if the file is correctly created.

About the non-Local-system account: I believe that is implemented. You can see it here: https://github.com/gocd/azure-elastic-agent-plugin/blob/1cf583d85809f86e0da502d95478affe17e88794/src/main/resources/windows_install_go_agent.template.flth#L46-L50

You should be able to set the username and password in the profile and it should use it, I think.

If not, you _might_ be able to use the elastic profile's configuration to add a script which can do that. For instance, this is one of the configs we've used:

<img width="1031" alt="2020_06_09_20-49-58" src="https://user-images.githubusercontent.com/172235/84193110-d8f36b80-aa92-11ea-952c-43630514a206.png">

**Comment by arvindsv** [comment]
There's also a plugin status page which you can get to from Admin -> Plugins -> and then the plugin. Not sure if it will be useful. If there are any logs on the Azure end, that might be useful too.

**Comment by aliensojurner** [comment]
I'll be taking a look at this, this evening. 

In regards to the service account, it's my understanding that the plugin creates the user account on the machine that goes with the username and password setting I setup in the plugin but when it installs the agent it will install it in a default way which makes it run under LocalSystem user. Are you referring to the user account or the account the service is running under. I know when I do a regular install of an agent I have to open the Services app in Windows and set that specific service to run under a specific user account through the service properties. Are you saying it should both create the account I configure and the logon as service in the Services app in Windows?

**Comment by aliensojurner** [comment]
Did you happen to uncover anything that would cause the agent to not show up under the Elastic Agents setting? 

As for the running as a service, it does look like it should be based on the code snippet you shared.

**Comment by arvindsv** [comment]
> Did you happen to uncover anything that would cause the agent to not show up under the Elastic Agents setting?

No. You'll need to check the autoregister properties file to see if it is created properly.

**Comment by aliensojurner** [comment]
I logged in to an elastic agent while it was running and found that it is not creating an autoregister.properties file in the C:\go-agent\config\ directory.

**Comment by aliensojurner** [comment]
scratch that. I'm not exactly sure what changed but it did create the autoregister.properties file. It only seemed to happen after I fixed a perforce issue but I'm not sure that was really the solution.

**Comment by aliensojurner** [comment]
I did get this in the console and it's not building - class com.thoughtworks.go.server.service.AgentRuntimeInfo cannot be cast to class com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo (com.thoughtworks.go.server.service.AgentRuntimeInfo and com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @6ce07fe); nested exception is java.lang.ClassCastException: class com.thoughtworks.go.server.service.AgentRuntimeInfo cannot be cast to class com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo (com.thoughtworks.go.server.service.AgentRuntimeInfo and com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @6ce07fe)

**Comment by arvindsv** [comment]
@aliensojurner Nice. That's useful. Thanks. I might need to look into it. Which version of the GoCD server are you using?

Are there any log messages in the GoCD server log file?

**Comment by aliensojurner** [comment]
As an aside, I think, though I need to test this theory, that the original GUID file for some unknown reason my be the problem. It showed up as a static agent which I deleted for testing reasons. Then I deleted the GUID file and waited for it to show back up in Static agents, but it finally wound up showing in Elastic agents. I'll report back on the GUID concern. 

I tried tracking down a specific run and put it in the attached file. Hopefully it will help.

**Comment by aliensojurner** [comment]
I'm not able to recreate getting the agent to show up as elastic. I got it to show up just one time. During that one time I did the following:
Deleted the Static agent when it appeared
Deleted the GUID file which recreated a new GUID file but the agent didn't reappear in Static
Logged into Perforce (which shouldn't as I understand it, have nothing to do with this)
Rebooted the VM
The agent showed up as Elastic. 

Those same steps repeated that way and in a couple different combinations did not get it to show back up in elastic agents. It's now still only showing up in static.

**Comment by arvindsv** [comment]
After a bit of trouble, I managed to set this up and could see that it did not bring up an elastic agent (brought up a normal agent, because of the fact that the autoregister.properties file wasn't created. 

Something likely happened in this script: https://github.com/gocd/azure-elastic-agent-plugin/blob/1cf583d85809f86e0da502d95478affe17e88794/src/main/resources/windows_install_go_agent.template.flth#L44 and I'm not sure where the logs from there go to. It didn't even show up in Windows' Event Viewer. I'll look into it later.

**Comment by aliensojurner** [comment]
Thank you. I'll await your research into this issue and possible fix. I'm trying to move some build machines into the cloud and using elastic agents is what I really want to be able to do. Your help in this matter has been greatly appreciated.

**Comment by arvindsv** [comment]
I turned on debug logs, as mentioned in the [troubleshooting documentation](https://github.com/gocd/azure-elastic-agent-plugin/blob/master/docs/TROUBLESHOOT.md). Once that was done, I saw this in the logs:

```
2020-06-16 15:15:02,501 DEBUG [179@MessageListener for CreateAgentListener] AzurePlugin:46 - server_url: https://my-gocd-server/go
plugin_id: com.thoughtworks.gocd.elastic-agent.azure
agent_id: gocd-azure-b75e6ac9-e404-4e08-af89-7382fa120352
environment:
go_agent_installer_url: https://download.gocd.org/binaries/20.1.0-11114/win/go-agent-20.1.0-11114-jre-64bit-setup.exe
Disabling User Access Control
Installing go-agent using command: .\go-agent-installer.exe /S /SERVERURL=`"https://my-gocd-server/go`" /START_AGENT=NO /D=C:\go-agent
Waiting 180 seconds for GoAgent service to install

Status   Name               DisplayName
------   ----               -----------
Stopped  Go Agent           Go Agent
Changing service to run as user: go

__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
ReturnValue      : 0
PSComputerName   :

Adding autoregister.properties file
2020-06-16 15:15:02,501 DEBUG [179@MessageListener for CreateAgentListener] AzurePlugin:46 - Exception calling "WriteAllLines" with "2" argument(s): "Could not find a part of the path
'C:\go-agent\config\autoregister.properties'."
At C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.5\Downloads\script0.ps1:57 char:1
+ [System.IO.File]::WriteAllLines("$install_dir\config\autoregister.pro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : DirectoryNotFoundException
```

From this, I could see that it had failed because `C:\go-agent\config` was not created yet (mainly because the agent was not yet started even once). So, I added a line in [this commit](https://github.com/gocd/azure-elastic-agent-plugin/commit/3273b9f2a638f658679099844e3a24c2a8fd40ea#diff-87496d65dd54f9fa1a49234469215149R57) to create that directory if needed (it is).

Once this was done, I could see the job finish successfully. Can you try https://github.com/gocd/azure-elastic-agent-plugin/releases/tag/v1.0.0-10-exp and see if it works?

**Comment by aliensojurner** [comment]
It seems that the latest iteration of the plugin it's no longer installing the agent or creating the `C:\go-agent` folder at all

**Comment by aliensojurner** [comment]
Thanks. I thought something else was broken but it seems not... I'll do some more testing and see if it's working properly.
